version: '3.7'
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 4000:4000

  client_ng:
    container_name: client_ng
    build: ./clientNg
    ports:
      - 4200:80